<?php

return [

    'free_gift_threshold' => 1000,

    'categories' => [
        ['slug' => 'cooking-essentials', 'name' => 'Cooking Essentials', 'icon' => 'oil'],
        ['slug' => 'honey-nuts',         'name' => 'Honey & Nuts',       'icon' => 'honey'],
        ['slug' => 'spices',             'name' => 'Spices',             'icon' => 'spice'],
        ['slug' => 'dairy',              'name' => 'Dairy',              'icon' => 'dairy'],
        ['slug' => 'dates',              'name' => 'Dates',              'icon' => 'dates'],
        ['slug' => 'beverages',          'name' => 'Beverages',          'icon' => 'tea'],
    ],

    'banners' => [
        [
            'image'    => 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1400&q=80',
            'headline' => 'Pure & Natural Groceries',
            'sub'      => 'Delivered to your door',
            'cta'      => 'Shop Now',
            'href'     => '/category/cooking-essentials',
        ],
        [
            'image'    => 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=1400&q=80',
            'headline' => 'Raw Honey Collection',
            'sub'      => 'Straight from the hive',
            'cta'      => 'Explore',
            'href'     => '/category/honey-nuts',
        ],
    ],

    'products' => [

        // ── cooking-essentials ──────────────────────────────────────────────
        [
            'slug'        => 'mustard-oil-1l',
            'name'        => 'Pure Mustard Oil 1L',
            'category'    => 'cooking-essentials',
            'price'       => 480,
            'old_price'   => 550,
            'badge'       => ['type' => 'save', 'label' => 'Save 13%'],
            'image'       => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
                'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80',
            ],
            'brand'       => 'Ghorer Bazar',
            'rating'      => 4.7,
            'reviews'     => 128,
            'in_stock'    => true,
            'description' => 'Cold-pressed pure mustard oil, rich aroma, no additives.',
        ],
        [
            'slug'        => 'soybean-oil-2l',
            'name'        => 'Soybean Oil 2L',
            'category'    => 'cooking-essentials',
            'price'       => 320,
            'old_price'   => null,
            'badge'       => ['type' => 'best', 'label' => 'Best Selling'],
            'image'       => 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
                'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80',
                'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
            ],
            'brand'       => 'Rupchanda',
            'rating'      => 4.5,
            'reviews'     => 214,
            'in_stock'    => true,
            'description' => 'Premium refined soybean oil, ideal for everyday cooking and deep frying.',
        ],
        [
            'slug'        => 'rice-bran-oil-1l',
            'name'        => 'Rice Bran Oil 1L',
            'category'    => 'cooking-essentials',
            'price'       => 390,
            'old_price'   => 430,
            'badge'       => ['type' => 'save', 'label' => 'Save 9%'],
            'image'       => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
                'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
            ],
            'brand'       => 'Teer',
            'rating'      => 4.3,
            'reviews'     => 76,
            'in_stock'    => true,
            'description' => 'Light rice bran oil with a high smoke point, perfect for stir-frying and sautéing.',
        ],

        // ── honey-nuts ───────────────────────────────────────────────────────
        [
            'slug'        => 'raw-honey-500g',
            'name'        => 'Raw Forest Honey 500g',
            'category'    => 'honey-nuts',
            'price'       => 650,
            'old_price'   => 750,
            'badge'       => ['type' => 'save', 'label' => 'Save 13%'],
            'image'       => 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
                'https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80',
                'https://images.unsplash.com/photo-1567718379428-f63e3a1c97af?w=800&q=80',
            ],
            'brand'       => 'Sundarban Honey',
            'rating'      => 4.8,
            'reviews'     => 342,
            'in_stock'    => true,
            'description' => 'Unprocessed raw forest honey harvested from the Sundarbans, full of natural enzymes.',
        ],
        [
            'slug'        => 'cashew-nuts-250g',
            'name'        => 'Premium Cashew Nuts 250g',
            'category'    => 'honey-nuts',
            'price'       => 420,
            'old_price'   => null,
            'badge'       => ['type' => 'new', 'label' => 'New Arrival'],
            'image'       => 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&q=80',
                'https://images.unsplash.com/photo-1567718379428-f63e3a1c97af?w=800&q=80',
            ],
            'brand'       => 'Ghorer Bazar',
            'rating'      => 4.6,
            'reviews'     => 57,
            'in_stock'    => true,
            'description' => 'Freshly sourced whole cashews, lightly roasted and packed for maximum freshness.',
        ],
        [
            'slug'        => 'almond-200g',
            'name'        => 'California Almonds 200g',
            'category'    => 'honey-nuts',
            'price'       => 380,
            'old_price'   => null,
            'badge'       => null,
            'image'       => 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
                'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&q=80',
            ],
            'brand'       => 'Nut Farm',
            'rating'      => 4.4,
            'reviews'     => 89,
            'in_stock'    => true,
            'description' => 'Raw California almonds, rich in healthy fats and protein, great as a daily snack.',
        ],

        // ── spices ───────────────────────────────────────────────────────────
        [
            'slug'        => 'turmeric-powder-200g',
            'name'        => 'Organic Turmeric Powder 200g',
            'category'    => 'spices',
            'price'       => 120,
            'old_price'   => null,
            'badge'       => ['type' => 'best', 'label' => 'Best Selling'],
            'image'       => 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80',
                'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80',
            ],
            'brand'       => 'Ghorer Bazar',
            'rating'      => 4.7,
            'reviews'     => 195,
            'in_stock'    => true,
            'description' => 'Pure organic turmeric powder with high curcumin content, no fillers or artificial color.',
        ],
        [
            'slug'        => 'red-chilli-powder-100g',
            'name'        => 'Red Chilli Powder 100g',
            'category'    => 'spices',
            'price'       => 85,
            'old_price'   => 100,
            'badge'       => ['type' => 'save', 'label' => 'Save 15%'],
            'image'       => 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80',
                'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80',
                'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
            ],
            'brand'       => 'Radhuni',
            'rating'      => 4.2,
            'reviews'     => 133,
            'in_stock'    => true,
            'description' => 'Fiery red chilli powder, sun-dried and stone-ground for authentic Bangladeshi flavor.',
        ],

        // ── dairy ────────────────────────────────────────────────────────────
        [
            'slug'        => 'full-cream-milk-1l',
            'name'        => 'Full Cream Milk 1L',
            'category'    => 'dairy',
            'price'       => 95,
            'old_price'   => null,
            'badge'       => null,
            'image'       => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80',
                'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=800&q=80',
            ],
            'brand'       => 'Milk Vita',
            'rating'      => 4.5,
            'reviews'     => 302,
            'in_stock'    => true,
            'description' => 'Fresh full-cream pasteurized milk, rich in calcium and vitamins for the whole family.',
        ],
        [
            'slug'        => 'dahi-500g',
            'name'        => 'Fresh Dahi (Yogurt) 500g',
            'category'    => 'dairy',
            'price'       => 75,
            'old_price'   => null,
            'badge'       => ['type' => 'new', 'label' => 'New Arrival'],
            'image'       => 'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=800&q=80',
                'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80',
            ],
            'brand'       => 'Aarong Dairy',
            'rating'      => 4.6,
            'reviews'     => 88,
            'in_stock'    => true,
            'description' => 'Creamy fresh dahi made from whole milk, perfect for raita, lassi, or eating plain.',
        ],

        // ── dates ────────────────────────────────────────────────────────────
        [
            'slug'        => 'medjool-dates-500g',
            'name'        => 'Medjool Dates 500g',
            'category'    => 'dates',
            'price'       => 580,
            'old_price'   => 650,
            'badge'       => ['type' => 'save', 'label' => 'Save 11%'],
            'image'       => 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
                'https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80',
            ],
            'brand'       => 'Al-Madina',
            'rating'      => 4.9,
            'reviews'     => 267,
            'in_stock'    => true,
            'description' => 'Soft and juicy premium Medjool dates from Saudi Arabia, naturally sweet and fiber-rich.',
        ],
        [
            'slug'        => 'ajwa-dates-250g',
            'name'        => 'Ajwa Dates 250g',
            'category'    => 'dates',
            'price'       => 490,
            'old_price'   => null,
            'badge'       => ['type' => 'best', 'label' => 'Best Selling'],
            'image'       => 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80',
                'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
                'https://images.unsplash.com/photo-1567718379428-f63e3a1c97af?w=800&q=80',
            ],
            'brand'       => 'Al-Madina',
            'rating'      => 4.8,
            'reviews'     => 183,
            'in_stock'    => true,
            'description' => 'Authentic Ajwa dates from Madinah, known for their distinct taste and health benefits.',
        ],

        // ── beverages ────────────────────────────────────────────────────────
        [
            'slug'        => 'green-tea-100g',
            'name'        => 'Organic Green Tea 100g',
            'category'    => 'beverages',
            'price'       => 250,
            'old_price'   => null,
            'badge'       => ['type' => 'new', 'label' => 'New Arrival'],
            'image'       => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
                'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80',
            ],
            'brand'       => 'Teatulia',
            'rating'      => 4.4,
            'reviews'     => 112,
            'in_stock'    => true,
            'description' => 'Premium loose-leaf organic green tea from the hills of Sylhet, light and antioxidant-rich.',
        ],
        [
            'slug'        => 'black-tea-200g',
            'name'        => 'Sylhet Black Tea 200g',
            'category'    => 'beverages',
            'price'       => 180,
            'old_price'   => 210,
            'badge'       => ['type' => 'save', 'label' => 'Save 14%'],
            'image'       => 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80',
                'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
                'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
            ],
            'brand'       => 'TAAZA',
            'rating'      => 4.6,
            'reviews'     => 289,
            'in_stock'    => true,
            'description' => 'Strong, full-bodied Sylhet black tea, perfect for brewing a traditional doodh cha.',
        ],
        [
            'slug'        => 'rose-water-250ml',
            'name'        => 'Pure Rose Water 250ml',
            'category'    => 'beverages',
            'price'       => 140,
            'old_price'   => null,
            'badge'       => null,
            'image'       => 'https://images.unsplash.com/photo-1559181567-c3190ca9d51c?w=600&q=80',
            'gallery'     => [
                'https://images.unsplash.com/photo-1559181567-c3190ca9d51c?w=800&q=80',
                'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
            ],
            'brand'       => 'Ghorer Bazar',
            'rating'      => 4.3,
            'reviews'     => 64,
            'in_stock'    => false,
            'description' => 'Food-grade pure rose water, ideal for desserts, sherbets, and biryani.',
        ],

    ],

];
